### ISSUE TITLE
Implement a Help system

### ISSUE THREAD

**Issue by ghost** [jakethedev/tavernbot#10]
Core: !help should list commands and what they need to run successfully. 

Advanced: I think the best way might be to have each function return some help text when invoked with a single parameter of 'help'. This allows us to be consistent across the app, and to iterate all the loaded functions of tavernlib/discordlib/etc and just concat all the help stuff together for a global "!help all" command

**Comment by jakethedev** [comment]
Leaving this here for notes on help docs: https://discordjs.guide/#/command-handling/adding-features?id=a-dynamic-help-command
