### ISSUE TITLE
Not a member?

### ISSUE THREAD

**Issue by j2l** [jakethedev/tavernbot#78]
Expand here on your title, unless the title is clear enough. Please delete any template lines that you aren't using - note that this is a suggested format, and though it's nice, you're not bound to it :)

### Bug Alert
me: `!newrole`
tavernbot on my discord server: `you don't even live here, stop messing with things (err: not a server member)`

me: `!addrole blacksmith`
tavernbot:
```
/app/discordlib/discordroles.js:21

  let requestorName = message.member.user.username

                                     ^


TypeError: Cannot read property 'user' of null
```

May be I missed something about player registration?

**Comment by jakethedev** [comment]
Mk, there's a few things going on here, mostly it's broken but there's more info on it

New-role is still unimplemented, it won't take long when I get a chance to sit down to it but it currently isn't functional - so I just set up issue #79 to track that one. 

That said, the error your getting is surprising - per the discord.js docs, there's a 'guild' built in under the covers of each server, and if you've joined a server you should automatically (to my understanding) be added to that guild, so this is new bug territory :) Discord.js provides a way to get the sender of the message as if they're a member of that guild, which is how I've been approaching all the role bits, but apparently that's not necessarily going to work.

You are the server admin, yeah? Can you link a screenshot of the roles page of your server so I can see what's there?

**Comment by j2l** [comment]
>  if you've joined a server
May be because the bot joined after me? Does it fire only when a new member joins?
Here are the role I've given to the bot, but it may be not correctly set, let me know:
![image](https://user-images.githubusercontent.com/65325/46457753-c0a65600-c7b3-11e8-9ba4-25215b7319b7.png)
![image](https://user-images.githubusercontent.com/65325/46457910-46c29c80-c7b4-11e8-85d0-36edb74b7209.png)

**Comment by jakethedev** [comment]
Currently there shouldn't be anything event-based with the bot, it's all text commands and doesn't do anything when someone joins (though there is a request for that in #76) - so I'm pretty stumped. I'll definitely look into this though, I'm stoked that someone else is using this haha

Interesting, thanks for the screen caps. Try creating a couple roles that are below the 'bot' role on the list, then using !addrole theRoleYouMade - does it still give you the same error?

**Comment by j2l** [comment]
OK, I found why it wasn't working:
Since the channel name was #general, I DM the bot and it couldn't find any channel to reply on.
Now that it's golemworks, it's working fine.

**Comment by jakethedev** [comment]
Ah ok, I should make sure to give it some usage info. Glad it's working for you!
